# Generated by Django 5.2.3 on 2025-06-10 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('slug', models.SlugField(unique=True, verbose_name='URL别名')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '药品分类',
                'verbose_name_plural': '药品分类',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='药品名称')),
                ('slug', models.SlugField(unique=True, verbose_name='URL别名')),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d', verbose_name='药品图片')),
                ('description', models.TextField(verbose_name='详细描述')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='库存')),
                ('available', models.BooleanField(default=True, verbose_name='是否上架')),
                ('prescription_required', models.BooleanField(default=False, verbose_name='是否处方药')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='分类')),
            ],
            options={
                'verbose_name': '药品',
                'verbose_name_plural': '药品',
                'ordering': ('-created',),
            },
        ),
    ]
